mybatis:
  type-aliases-package: com.triplan.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  resources:
    location: C:\Users\yeon\Desktop\triplan\Triplan #실제 공통 경로
