mybatis:
  type-aliases-package: com.triplan.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  resources:
    location: D:\Upload #실제 공통 경로
    commonUrl: /resources